from datetime import datetime
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
    func,
)
from sqlalchemy.orm import relationship

from db.session import Base


class Profile(Base):
    """User profile representing fans, volunteers, or organizers, linked to Supabase Auth ID."""

    __tablename__ = "profiles"

    id = Column(String, primary_key=True)  # Matches Supabase UUID
    email = Column(String, unique=True, index=True, nullable=False)
    full_name = Column(String, nullable=True)
    role = Column(String, default="fan", nullable=False)  # fan, volunteer, organizer
    preferences = Column(JSON, nullable=True)  # Accessibility, seat info, language
    created_at = Column(DateTime, default=func.now(), nullable=False)
    updated_at = Column(
        DateTime, default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    incidents = relationship("Incident", back_populates="reporter")
    tasks = relationship("VolunteerTask", back_populates="assignee")


class Zone(Base):
    """Stadium zone containing crowd capacity and current density levels."""

    __tablename__ = "zones"

    id = Column(String, primary_key=True)  # e.g., "zone-a", "zone-b"
    name = Column(String, nullable=False)
    capacity = Column(Integer, default=5000, nullable=False)
    current_crowd_count = Column(Integer, default=0, nullable=False)
    density_level = Column(String, default="low", nullable=False)  # low, medium, high, critical

    # Relationships
    facilities = relationship("Facility", back_populates="zone")
    incidents = relationship("Incident", back_populates="zone")
    alerts = relationship("LiveAlert", back_populates="zone")


class Facility(Base):
    """Stadium facilities like restrooms, concession stands, first aid, accessibility ramps."""

    __tablename__ = "facilities"

    id = Column(String, primary_key=True)  # e.g., "restroom-1", "food-1"
    name = Column(String, nullable=False)
    type = Column(String, nullable=False)  # restroom, food, first_aid, merchandise, gate, accessibility
    zone_id = Column(String, ForeignKey("zones.id"), nullable=False)
    is_accessible = Column(Boolean, default=True, nullable=False)
    status = Column(String, default="open", nullable=False)  # open, crowded, closed
    wait_time_minutes = Column(Integer, default=0, nullable=False)
    location_x = Column(Float, default=0.0, nullable=False)  # Visual placement coordinate
    location_y = Column(Float, default=0.0, nullable=False)  # Visual placement coordinate

    # Relationships
    zone = relationship("Zone", back_populates="facilities")


class Incident(Base):
    """Operational incidents reported by staff, volunteers, or AI alerts."""

    __tablename__ = "incidents"

    id = Column(String, primary_key=True)
    reporter_id = Column(String, ForeignKey("profiles.id"), nullable=True)
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    zone_id = Column(String, ForeignKey("zones.id"), nullable=False)
    severity = Column(String, default="low", nullable=False)  # low, medium, high, critical
    status = Column(String, default="reported", nullable=False)  # reported, investigating, resolved, escalated
    ai_summary = Column(Text, nullable=True)
    sop_steps = Column(JSON, nullable=True)  # SOP tasks generated by AI
    created_at = Column(DateTime, default=func.now(), nullable=False)
    updated_at = Column(
        DateTime, default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    reporter = relationship("Profile", back_populates="incidents")
    zone = relationship("Zone", back_populates="incidents")
    tasks = relationship("VolunteerTask", back_populates="incident")


class VolunteerTask(Base):
    """Action items assigned to volunteers to resolve incidents or perform standard duties."""

    __tablename__ = "volunteer_tasks"

    id = Column(String, primary_key=True)
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    assigned_to = Column(String, ForeignKey("profiles.id"), nullable=False)
    incident_id = Column(String, ForeignKey("incidents.id"), nullable=True)
    status = Column(String, default="pending", nullable=False)  # pending, in_progress, completed
    created_at = Column(DateTime, default=func.now(), nullable=False)
    completed_at = Column(DateTime, nullable=True)

    # Relationships
    assignee = relationship("Profile", back_populates="tasks")
    incident = relationship("Incident", back_populates="tasks")


class LiveAlert(Base):
    """Urgent broadcasts sent to fans, volunteers, or operations organizers."""

    __tablename__ = "live_alerts"

    id = Column(String, primary_key=True)
    title = Column(String, nullable=False)
    message = Column(Text, nullable=False)
    target_role = Column(String, default="all", nullable=False)  # all, fan, volunteer, organizer
    zone_id = Column(String, ForeignKey("zones.id"), nullable=True)
    severity = Column(String, default="info", nullable=False)  # info, warning, critical
    created_at = Column(DateTime, default=func.now(), nullable=False)
    expires_at = Column(DateTime, nullable=True)

    # Relationships
    zone = relationship("Zone", back_populates="alerts")
